[package]
name = "ellex_web"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Ellex web component"

[dependencies]
ellex_core = { path = "../ellex_core" }
serde.workspace = true
anyhow.workspace = true
